version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    container_name: chounai_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chounai_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
